#!/bin/sh

while [ 1 ]
do
    echo "data_center not running." 
	killall dropbear
	killall udhcpc
	killall nmbd
	killall mDNSResponderPosix
	killall zconf.sh
	killall zero_conf_vz
	killall zero_conf_telus
	killall wget
	rm -f /tmp/get_parameters.telus.xml
	rm -f /tmp/upgrade_url.xml
	killall clinkd
	killall cli 
	data_center
done


